# Generated by Django 5.2.12 on 2026-04-10 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
