# Generated by Django 5.2.12 on 2026-04-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_created_time_author_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='books',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
